
artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL:https://github.com/jr-jyc1/DC-01/raw/refs/heads/main/DC%2001.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
